Repository rko0211/jgec-previous-year-question-paper, pull requests merged in 2024-01, with the labels that each got.

#12 Add new features to nav bar and changed the background of the navbar
  styles.css
Labels: good first issue, medium, Apertre

#17 Test
  styles.css
Labels: medium, Apertre

#24 issue #2 / README
  README.md
  readme logo.jpeg
Labels: good first issue, Easy, apertre, apertre24

#31 #5 Purpose page created
  .vscode/c_cpp_properties.json
  .vscode/launch.json
  .vscode/settings.json
  Mission.webp
  Values.jpeg
  benefits.png
  build/Debug/candies.o
  build/Debug/food_animal.o
  conclusion.png
  index.html
  objective.png
  purposepage.css
  purposepage.html
  purposepage.js
  styles.css
Labels: good first issue, Hard, apertre, apertre24

#26 Added Mail Redirection Button
  index.html
Labels: bug, Easy, apertre, apertre24

#44 Added favicons
  Firstyear/First_sem_Second_sem/first_sem_second_sem_ce.html
  Firstyear/First_sem_Second_sem/first_sem_second_sem_cs.html
  Firstyear/First_sem_Second_sem/first_sem_second_sem_ec.html
  Firstyear/First_sem_Second_sem/first_sem_second_sem_ee.html
  Firstyear/First_sem_Second_sem/first_sem_second_sem_it.html
  Firstyear/First_sem_Second_sem/first_sem_second_sem_me.html
  Firstyear/first_year.html
  Fourthyear/Seventh_sem_Eight_sem/seven_sem_eight_sem_ce.html
  Fourthyear/Seventh_sem_Eight_sem/seven_sem_eight_sem_cs.html
  Fourthyear/Seventh_sem_Eight_sem/seven_sem_eight_sem_ec.html
  Fourthyear/Seventh_sem_Eight_sem/seven_sem_eight_sem_ee.html
  Fourthyear/Seventh_sem_Eight_sem/seven_sem_eight_sem_it.html
  Fourthyear/Seventh_sem_Eight_sem/seven_sem_eight_sem_me.html
  Fourthyear/fourth_year.html
  Secondyear/Third_sem_Fourth_sem/third_sem_fourth_sem_ce.html
  Secondyear/Third_sem_Fourth_sem/third_sem_fourth_sem_cs.html
  Secondyear/Third_sem_Fourth_sem/third_sem_fourth_sem_ec.html
  Secondyear/Third_sem_Fourth_sem/third_sem_fourth_sem_ee.html
  Secondyear/Third_sem_Fourth_sem/third_sem_fourth_sem_it.html
  Secondyear/Third_sem_Fourth_sem/third_sem_fourth_sem_me.html
  Secondyear/second_year.html
  Thirdyear/Fifth_sem_sixth_sem/fifth_sem_sixth_sem_ce.html
  Thirdyear/Fifth_sem_sixth_sem/fifth_sem_sixth_sem_cs.html
  Thirdyear/Fifth_sem_sixth_sem/fifth_sem_sixth_sem_ec.html
  Thirdyear/Fifth_sem_sixth_sem/fifth_sem_sixth_sem_ee.html
  Thirdyear/Fifth_sem_sixth_sem/fifth_sem_sixth_sem_it.html
  Thirdyear/Fifth_sem_sixth_sem/fifth_sem_sixth_sem_me.html
  Thirdyear/third_year.html
  favicons/year1.png
  favicons/year2.png
  favicons/year3.png
  favicons/year4.png
Labels: Easy, apertre, apertre24

#50 Update README.md
  README.md
Labels: Easy, apertre, apertre24

#47 #29 Added footer
  Firstyear/First_sem_Second_sem/first_sem_second_sem_cs.css
  Fourthyear/Seventh_sem_Eight_sem/channels4_profile.jpg
  Fourthyear/Seventh_sem_Eight_sem/email.png
  Fourthyear/Seventh_sem_Eight_sem/location.png
  Fourthyear/Seventh_sem_Eight_sem/seven_sem_eight_sem_ce.html
  Fourthyear/Seventh_sem_Eight_sem/seven_sem_eight_sem_cs.css
  Fourthyear/Seventh_sem_Eight_sem/seven_sem_eight_sem_cs.html
  Fourthyear/Seventh_sem_Eight_sem/seven_sem_eight_sem_ec.html
  Fourthyear/Seventh_sem_Eight_sem/seven_sem_eight_sem_ee.html
  Fourthyear/Seventh_sem_Eight_sem/seven_sem_eight_sem_it.html
  Fourthyear/Seventh_sem_Eight_sem/seven_sem_eight_sem_me.html
  Secondyear/Third_sem_Fourth_sem/channels4_profile.jpg
  Secondyear/Third_sem_Fourth_sem/email.png
  Secondyear/Third_sem_Fourth_sem/location.png
  Secondyear/Third_sem_Fourth_sem/third_sem_fourth_sem_ce.html
  Secondyear/Third_sem_Fourth_sem/third_sem_fourth_sem_cs.css
  Secondyear/Third_sem_Fourth_sem/third_sem_fourth_sem_cs.html
  Secondyear/Third_sem_Fourth_sem/third_sem_fourth_sem_ec.html
  Secondyear/Third_sem_Fourth_sem/third_sem_fourth_sem_ee.html
  Secondyear/Third_sem_Fourth_sem/third_sem_fourth_sem_it.html
  Secondyear/Third_sem_Fourth_sem/third_sem_fourth_sem_me.html
  Thirdyear/Fifth_sem_sixth_sem/channels4_profile.jpg
  Thirdyear/Fifth_sem_sixth_sem/email.png
  Thirdyear/Fifth_sem_sixth_sem/fifth_sem_sixth_sem_ce.html
  Thirdyear/Fifth_sem_sixth_sem/fifth_sem_sixth_sem_cs.css
  Thirdyear/Fifth_sem_sixth_sem/fifth_sem_sixth_sem_cs.html
  Thirdyear/Fifth_sem_sixth_sem/fifth_sem_sixth_sem_ec.html
  Thirdyear/Fifth_sem_sixth_sem/fifth_sem_sixth_sem_ee.html
  Thirdyear/Fifth_sem_sixth_sem/fifth_sem_sixth_sem_it.html
  Thirdyear/Fifth_sem_sixth_sem/fifth_sem_sixth_sem_me.html
  Thirdyear/Fifth_sem_sixth_sem/location.png
Labels: Easy, apertre, apertre24

#55 Update README.md
  README.md
Labels: Easy, apertre, apertre24

#56 #52 issue solved
  aos/aos.css
  aos/aos.js
  index.html
  index.js
  styles.css
Labels: Easy, apertre, apertre24

#58 #4 Created about page
  Purpose page/Purpose.html
  about.css
  about.html
  about.js
  img-1.avif
  img-4.png
  img-5.png
  img-6.jpg
  img2.png
  img3.png
  index.html
Labels: Easy, apertre, apertre24
